#!/bin/bash

# Vim
brew install vim --with-clientserver --with-client-server --override-system-vim
curl 'http://vim-bootstrap.com/generate.vim' --data 'langs=go&langs=python&langs=c&langs=javascript&langs=php&langs=html&langs=ruby&editor=vim' > ~/.vimrc

ln -s vimrc.local ~/.vimrc.local
ln -s vimrc.bundles.local ~/.vimrc.bundles.local


brew cask install mactex #includes latexmk which are needed for compiling of latex


brew install kubectl docker-machine-driver-xhyve
brew cask install minikube


# zsh

## Set default shell to zsh
chsh -s $(which zsh)

## Fonts
# clone
git clone https://github.com/powerline/fonts.git --depth=1
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts

## iTerm
# Get config from https://github.com/altercation/solarized
# Set font to ...

## Install thefuck
pip3 install thefuck
